In [1]:
import numpy as np
from sklearn.datasets import fetch_california_housing

housing = fetch_california_housing()
m, n = housing.data.shape

In [2]:
housing.data.shape

(20640, 8)

In [3]:
import tensorflow as tf

In [7]:
housing_data=housing.data

In [11]:
housing_data_with_bias=np.c_[np.ones((m,1)), housing_data]


In [12]:
housing_data_with_bias

array([[   1.        ,    8.3252    ,   41.        , ...,    2.55555556,
          37.88      , -122.23      ],
       [   1.        ,    8.3014    ,   21.        , ...,    2.10984183,
          37.86      , -122.22      ],
       [   1.        ,    7.2574    ,   52.        , ...,    2.80225989,
          37.85      , -122.24      ],
       ..., 
       [   1.        ,    1.7       ,   17.        , ...,    2.3256351 ,
          39.43      , -121.22      ],
       [   1.        ,    1.8672    ,   18.        , ...,    2.12320917,
          39.43      , -121.32      ],
       [   1.        ,    2.3886    ,   16.        , ...,    2.61698113,
          39.37      , -121.24      ]])

In [29]:
y=housing.target

In [20]:
X = tf.constant(housing_data_with_bias, dtype=tf.float32, name="X")

In [30]:
y = tf.constant(y.reshape(-1,1), dtype=tf.float32, name="y")

In [31]:
XT=tf.transpose(X)

In [33]:
thetha=tf.matmul(tf.matmul(tf.matrix_inverse(tf.matmul(XT, X)), XT),y)

In [34]:
with tf.Session() as sess:
    m=sess.run(thetha)
    print(m)


[[ -3.74651413e+01]
 [  4.35734153e-01]
 [  9.33829229e-03]
 [ -1.06622010e-01]
 [  6.44106984e-01]
 [ -4.25131839e-06]
 [ -3.77322501e-03]
 [ -4.26648885e-01]
 [ -4.40514028e-01]]


In [36]:
with tf.Session() as sess:
    theta_value = thetha.eval()
    print(theta_value)

[[ -3.74651413e+01]
 [  4.35734153e-01]
 [  9.33829229e-03]
 [ -1.06622010e-01]
 [  6.44106984e-01]
 [ -4.25131839e-06]
 [ -3.77322501e-03]
 [ -4.26648885e-01]
 [ -4.40514028e-01]]
