In [1]:
import numpy as np
from sklearn.datasets import fetch_california_housing

housing = fetch_california_housing()
m, n = housing.data.shape

In [2]:
housing.data.shape

(20640, 8)

In [3]:
import tensorflow as tf

In [4]:
housing_data=housing.data

In [5]:
housing_data_with_bias=np.c_[np.ones((m,1)), housing_data]


In [6]:
housing_data_with_bias

array([[   1.        ,    8.3252    ,   41.        , ...,    2.55555556,
          37.88      , -122.23      ],
       [   1.        ,    8.3014    ,   21.        , ...,    2.10984183,
          37.86      , -122.22      ],
       [   1.        ,    7.2574    ,   52.        , ...,    2.80225989,
          37.85      , -122.24      ],
       ...,
       [   1.        ,    1.7       ,   17.        , ...,    2.3256351 ,
          39.43      , -121.22      ],
       [   1.        ,    1.8672    ,   18.        , ...,    2.12320917,
          39.43      , -121.32      ],
       [   1.        ,    2.3886    ,   16.        , ...,    2.61698113,
          39.37      , -121.24      ]])

In [7]:
y=housing.target

In [8]:
X = tf.constant(housing_data_with_bias, dtype=tf.float32, name="X")

In [9]:
y = tf.constant(y.reshape(-1,1), dtype=tf.float32, name="y")

In [11]:
XT=tf.transpose(X)

In [12]:
thetha=tf.matmul(tf.matmul(tf.matrix_inverse(tf.matmul(XT, X)), XT),y)

In [13]:
with tf.Session() as sess:
    m=sess.run(thetha)
    print(m)


[[-3.7185181e+01]
 [ 4.3633747e-01]
 [ 9.3952334e-03]
 [-1.0711310e-01]
 [ 6.4479220e-01]
 [-4.0338000e-06]
 [-3.7813708e-03]
 [-4.2348403e-01]
 [-4.3721911e-01]]


In [14]:
with tf.Session() as sess:
    theta_value = thetha.eval()
    print(theta_value)

[[-3.7185181e+01]
 [ 4.3633747e-01]
 [ 9.3952334e-03]
 [-1.0711310e-01]
 [ 6.4479220e-01]
 [-4.0338000e-06]
 [-3.7813708e-03]
 [-4.2348403e-01]
 [-4.3721911e-01]]


In [10]:
X = tf.constant(housing_data_with_bias, dtype=tf.float32, name="X")

theta=tf.Variable(tf.random_uniform([n+1, 1], -1.0, 1.0), name="theta")

In [11]:
y_pred=tf.matmul(X, theta, name="predictions")

In [12]:
error=y_pred-y

In [13]:
mse=tf.reduce_mean(tf.square(error), name="mse")

In [14]:
gradients=2/m*tf.matmul(tf.transpose(X), error)

In [15]:
n_epochs = 1000
learning_rate = 0.01

In [16]:
training_op=tf.assign(theta, theta-learning_rate*gradients)

In [17]:
init=tf.global_variables_initializer()

In [18]:
with tf.Session() as sess:
    sess.run(init)
    for epoch in range(n_epochs):
        if (epoch % 100==0):
            print("Epoch:", epoch, " mse:", mse.eval())
        sess.run(training_op)
    best_theta=theta.eval()

Epoch: 0  mse: 210379.28
Epoch: 100  mse: nan
Epoch: 200  mse: nan
Epoch: 300  mse: nan
Epoch: 400  mse: nan
Epoch: 500  mse: nan
Epoch: 600  mse: nan
Epoch: 700  mse: nan
Epoch: 800  mse: nan
Epoch: 900  mse: nan


In [30]:
best_theta

array([[nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan]], dtype=float32)

In [21]:
n_epochs = 1000
learning_rate = 0.01

X = tf.constant(housing_data_with_bias, dtype=tf.float32, name="X")
y = tf.constant(housing.target.reshape(-1, 1), dtype=tf.float32, name="y")
theta = tf.Variable(tf.random_uniform([n + 1, 1], -1.0, 1.0), name="theta")
y_pred = tf.matmul(X, theta, name="predictions")
error = y_pred - y
mse = tf.reduce_mean(tf.square(error), name="mse")
gradients = tf.gradients(mse, [theta])[0]
training_op = tf.assign(theta, theta - learning_rate * gradients)

init = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init)

    for epoch in range(n_epochs):
        if epoch % 100 == 0:
            print("Epoch", epoch, "MSE =", mse.eval())
        sess.run(training_op)

    best_theta = theta.eval()

Epoch 0 MSE = 1992867.1
Epoch 100 MSE = nan
Epoch 200 MSE = nan
Epoch 300 MSE = nan
Epoch 400 MSE = nan
Epoch 500 MSE = nan
Epoch 600 MSE = nan
Epoch 700 MSE = nan
Epoch 800 MSE = nan
Epoch 900 MSE = nan
